### ISSUE TITLE
Weapon/Book

### ISSUE THREAD

**Issue by haxxnshine** [TUMS-SAU/SAU-0.5#10]
## ✅ Checklist
- [ ] ㄱㄱㄱ
- [ ] ㄴㄴㄴ

## ✏ Description
- 근거리 공격형 무기 
- Lv.1 : 공격력 15, 공속 2초, 투과 무한, 플레이어가 보는 방향으로 10px

<img width="607" alt="Pasted Graphic" src="https://github.com/TUMS-SAU/SAU-0.5/assets/104686632/902c2c83-5535-4e77-a65e-894865a5e1c0"> 

## 📋 TODO
-  [ ] 레벨업을 할수록 전공책이 더 두꺼워지고, 공격속도, 공격력이 증가 
- [ ] 플레이어가 보는 방향에 따라서 휘두르는 방향이 달라짐
- [ ] 휘두를 때 가능하다면 살짝 열리는 애니메이션 
- [ ] 휘두를때마다 공격이 들어가도록 구현, 그 찰나에 순간에만 들어가도록
- [ ] 두께 바뀌는 거 구현 필요 (레벨업마다 스프라이트 바꿔주기)
