### ISSUE TITLE
Eco Bag

### ISSUE THREAD

**Issue by melitina915** [TUMS-SAU/SAU-0.5#12]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- 신입생 에코백
    - 채찍

## 📋 TODO
- [x] 신입생 에코백 : 채찍
