### ISSUE TITLE
UI-START

### ISSUE THREAD

**Issue by haxxnshine** [TUMS-SAU/SAU-0.5#13]
## ✅ Checklist
- [ ] 
- [ ] 

## ✏ Description
- 상단 : 스피커, 설정, 인스타그램
- 중간 : 게임 로고
- 하단 : "화면을 터치하면 게임이 시작됩니다!"
- 화면 전체 : 화면을 터치하면 캐릭터 선택 UI로 넘어가는 기능

## 📋 TODO
- [x] 화면을 아무데나 터치하면 캐릭터 선택 화면으로 넘어가는 기능
- [x] 게임이 시작되자마자 배경음악 나오기 -> 게임에 나오는 음악과 달라도 괜찮을거 같다.
- [x] 인스타버튼 클릭하면 TUMS 인스타로 넘어감
- [x] 설정 창만 구현
