### ISSUE TITLE
UI-Character Scene

### ISSUE THREAD

**Issue by haxxnshine** [TUMS-SAU/SAU-0.5#14]
## ✅ Checklist
- [ ] 
- [ ] 

## ✏ Description
- 상단 : "마음에 드는 캐릭터를 선택해주세요!"
- 중간 : 캐릭터 선택 버튼
- 하단 : 맵 선택으로 넘어가는 버튼

## 📋 TODO
- [ ] 캐릭터를 선택하고 "맵 선택하기" 버튼을 누르면 다음 장면으로 넘어감
- [ ] 각 캐릭터에 맞게 이미지와 설명 추가
- [ ] 캐릭터 선택 구현 -> GameManager에서 Playerid랑 연결시키기
- [ ] 버튼 눌릴 때 제대로 눌리게 하기
- [x] BGM 
- [ ] 다른 버튼 누르면 업데이트 때 개선된다고 경고 -> 팝업 창
