### ISSUE TITLE
UI-Map Scene

### ISSUE THREAD

**Issue by haxxnshine** [TUMS-SAU/SAU-0.5#15]
## ✅ Checklist
- [ ] 
- [ ] 

## ✏ Description
- 상단 : "마음에 드는 맵을 선택해주세요!"
- 중간 : 맵 선택 버튼
- 하단 : 게임으로 넘어가는 버튼

## 📋 TODO
- [x] 맵을 선택하고 "게임 시작!" 버튼을 누르면 게임으로 넘어감
- [ ] 각 맵에 맞게 이미지와 설명 추가
- [ ] 맵을 선택하지 않고 버튼을 누르면 경고 멘트 -> 논의
- [ ] 맵 선택 구현 -> GameManager에서 연결시키기
- [x] 뒤로가기 버튼
- [ ] 버튼 눌릴 때 제대로 눌리게 하기
- [x] BGM 
- [ ] 다른 버튼 누르면 업데이트 때 개선된다고 경고
